Repository OISF/suricata-verify, pull requests merged in 2023-12, with the labels that each got.

#1506 tests: add test for pgsql probe bug 6080 - v3
  tests/pgsql-bug-6080-probe-test-01/README.md
  tests/pgsql-bug-6080-probe-test-01/input.pcap
  tests/pgsql-bug-6080-probe-test-01/suricata.yaml
  tests/pgsql-bug-6080-probe-test-01/test.yaml
  tests/pgsql-bug-6080-probe-test-01/writepcap.py
Labels: requires suricata pr, requires backport

#1533 detect/transform/header_lowercase: support from 7.0.3
  tests/transform-header-lowercase/test.yaml
Labels: requires suricata pr

#1553 test/pgsql: update cancel request min-version test - v1
  tests/pgsql/pgsql-cancel-request/test.yaml
Labels: requires backport
