Repository OISF/suricata-verify, pull requests merged in 2024-05, with the labels that each got.

#1806 tls/random: set min version to 7
  tests/tls/tls-random-6989/test.yaml
  tests/tls/tls-random/test.yaml
Labels: requires backport

#1821 fast_pattern w base64 data/v10
  tests/bug-5220/bug-5220-1/README.md
  tests/bug-5220/bug-5220-1/test.rules
  tests/bug-5220/bug-5220-1/test.yaml
  tests/bug-5220/bug-5220-2/README.md
  tests/bug-5220/bug-5220-2/test.rules
  tests/bug-5220/bug-5220-2/test.yaml
  tests/bug-5220/bug-5220-3/README.md
  tests/bug-5220/bug-5220-3/test.rules
  tests/bug-5220/bug-5220-3/test.yaml
  tests/bug-5220/bug-5220-4/README.md
  tests/bug-5220/bug-5220-4/test.rules
  tests/bug-5220/bug-5220-4/test.yaml
  tests/bug-5220/bug-5220-5/README.md
  tests/bug-5220/bug-5220-5/test.rules
  tests/bug-5220/bug-5220-5/test.yaml
  tests/bug-5220/bug-5220-6/README.md
  tests/bug-5220/bug-5220-6/test.rules
  tests/bug-5220/bug-5220-6/test.yaml
  tests/bug-5220/bug-5220-7/README.md
  tests/bug-5220/bug-5220-7/test.rules
  tests/bug-5220/bug-5220-7/test.yaml
Labels: requires suricata pr

#1838 Adds a test case for uri with space in it
  tests/http-uri-spaces/README.md
  tests/http-uri-spaces/input.pcap
  tests/http-uri-spaces/test.rules
  tests/http-uri-spaces/test.yaml
Labels: tests pass
