Repository OISF/suricata-verify, pull requests merged in 2024-09, with the labels that each got.

#2020 pgsql: update bug-6983 tests - v1
  tests/pgsql/pgsql-bug-6983-ids/README.md
  tests/pgsql/pgsql-bug-6983-ids/suricata.yaml
  tests/pgsql/pgsql-bug-6983-ids/test.yaml
  tests/pgsql/pgsql-bug-6983-ips/test.yaml
Labels: requires suricata pr

#2028 tls/ja3: adds test with duplicate handshake
  tests/tls-duplicate-hello/README.md
  tests/tls-duplicate-hello/cli.py
  tests/tls-duplicate-hello/input.pcap
  tests/tls-duplicate-hello/srv.go
  tests/tls-duplicate-hello/test.rules
  tests/tls-duplicate-hello/test.yaml
Labels: requires suricata pr

#2031 tls/ja3: backport test with duplicate handshake
  tests/tls-duplicate-hello/test.yaml
Labels: requires backport

#2061 tests: enable 7264 test for 7.0.7
  tests/bug-7264-tcp-3whs-ack-data-tls-01/test.yaml
Labels: requires suricata pr, requires backport
